### ISSUE TITLE
请问你的内存是什么型号

### ISSUE THREAD

**Issue by seac2020** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#1]
请问你的内存是什么型号，12代U听说对DDR4 3600支持的不好，开XMP的话只能3200才行。你这这套配置可有问题。还是说跟主板有关系。

**Comment by igarashikenshin** [comment]
跟主板有关，我内存是3200频的，手动可以超到4000，为了稳定降到3600使用的

**Comment by seac2020** [comment]
好的谢谢，开XMP都正常吧。

**Comment by seac2020** [comment]
我准备用你这套的EFI买这款主板和CPU，这套目前除了随航不能用外，其他都正常吧，BIOS里面要把核显关掉吧。

**Comment by igarashikenshin** [comment]
嗯

**Comment by seac2020** [comment]
我CPU用12900K的话也没问题吧，你这套EFI
