### ISSUE TITLE
6600xt登录前黑屏

### ISSUE THREAD

**Issue by leonmiguel** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#2]
你好啊兄弟，我6600xt安装13更新后进登录界面前一刻黑屏，然后一直没法进入系统，加了黑屏参数pikera 等也没用，我和你一样的板U，之前12系统是正常的。

**Comment by igarashikenshin** [comment]
mac pro机型不需要加载weg及pikera参数
黑屏可尝试关闭显示器开机，开机后点亮显示器查看是否恢复，若未恢复的话在boot args加-v参数看是否哪里有异常

发自我的 iPhone

在 2022年6月14日，00:32，leonmiguel ***@***.***> 写道：

﻿

你好啊兄弟，我6600xt安装13更新后进登录界面前一刻黑屏，然后一直没法进入系统，加了黑屏参数pikera 等也没用。之前12系统是正常的。

**Comment by leonmiguel** [comment]
![IMG_2165](https://user-images.githubusercontent.com/52582588/173471771-b2a7a339-5472-4f35-b044-d2417077361c.jpg)
谢谢楼主的秒回啊！试了楼主建议的方法，还是不行。这个是报错的截图，报错后，它就瞬间黑屏。然后查了下，应该是和硬盘有关的，我试着进去13的恢复模式，可以进，里面可以看到硬盘已经被升级为13了。

**Comment by igarashikenshin** [comment]
是OTA全量更新还是增量更新？用的是BCM网卡还是intel的？硬盘是三星还是其他？

**Comment by leonmiguel** [comment]
是全量更新，十几G那个；网卡是博通的拆机免驱卡；硬盘是西部数据的sn810。

**Comment by igarashikenshin** [comment]
显卡是公版还是非公？

**Comment by leonmiguel** [comment]
显卡是非公，迪兰战将6600xt。奇怪的是11，12版本都好好的，更新13时也一切顺利，各个安装阶段都没出问题，就是安装成功之后最后一步进系统就黑屏。但是硬盘和恢复模式都变成13了。我能力有限，也没搞明白什么情况，或许再等等后面稳定版本。谢谢楼主的时间和解答了。

**Comment by igarashikenshin** [comment]
非公仿冒一下，应该就没问题了

2022年6月16日 14:40，leonmiguel ***@***.***> 写道：



显卡是非公，迪兰战将6600xt。奇怪的是11，12版本都好好的，更新13时也一切顺利，各个安装阶段都没出问题，就是安装成功之后最后一步进系统就黑屏。但是硬盘和恢复模式都变成13了。我能力有限，也没搞明白什么情况，或许再等等后面稳定版本。谢谢楼主的时间和解答了。

**Comment by leonmiguel** [comment]
好的，我试下，谢谢你了！
