### ISSUE TITLE
CNVI网卡问题

### ISSUE THREAD

**Issue by tian9246** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#3]
虽然内置WIFI/BT模块已经可以通过AirportItlwm.kext、IntelBluetoothFirmware.kext、IntelBluetoothInjector.kext进行驱动并实现上网、接力功能，但因无法隔空投送，故我在BIOS中进行了屏蔽，使用了外置（PCI-E 转接）WIFI/BT模块。如果你想要用内置WIFI/BT模块，可以在以下链接下载kext（[IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases)、[AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases)），载入到OC中驱动使用。
这个的有点小问题，虽然Z690 EDGE自带AX201但是由于插入CNVI的槽里，无法通过 itlwm等驱动，只能拆散热片拔下来 ，插入其他PCIE槽内。

**Comment by igarashikenshin** [comment]
BIOS中屏蔽即可，不需要拔出

**Comment by tian9246** [comment]
屏蔽掉就不能通过AirportItlwm驱动了吧？

**Comment by igarashikenshin** [comment]
我之前测试是可以不用拆出就能驱动的，只是我用的博通pcie网卡，所以将内置屏蔽了

**Comment by tian9246** [comment]
请教下，当时驱动AX201，不需要任何BIOS设置，直接使用AirportItlwm.kext就可以么？OC的config需要改么？

**Comment by igarashikenshin** [comment]
Onboard CNVi Module Control的值改为enable，oc config中加载AirportItlwm.kext即可。

2022年6月16日 11:19，Hansen.tian ***@***.***> 写道：



请教下，当时驱动AX201，不需要任何BIOS设置，直接使用AirportItlwm.kext就可以么？OC的config需要改么？

**Comment by tian9246** [comment]
主板RMA之后，网卡已经正常工作
