### ISSUE TITLE
请教一些这个主板的问题，谢谢。

### ISSUE THREAD

**Issue by SherlockGougou** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#4]
我想装两个显卡，一个RTX3080Ti，一个RX460，分别对应Windows和macOS；
在Windows通过设备管理禁用RX460，在macOS中通过OC禁用RTX3080Ti；
- 请问这个板子的PCIE插口，能满足以上两个卡的带宽要求吗？
- 如果另外再插入两个4.0的M2呢？

**Comment by flipphos** [comment]
你第一个问题应该不存在，因为你一个时间只会用一张显卡，最多只需要16x pcie3.0带宽。

“12代酷睿处理器可提供16条PCIe 5.0通道和4条PCIe 4.0通道，总计20个通道。Z690芯片组则提供12个PCIe 4.0和16个PCIe 3.0通道。”

个人使用很难在某个时间点跑满这么多通道吧。能用设备占满（插满）倒是可能的。

**Comment by SherlockGougou** [comment]
意思是屏蔽后的显卡不会占用PCIE带宽嘛？我看别人提到说，黑苹果没办法完全禁用独立显卡，无论是SSDT该是参数，独立显卡都会有功耗且不低。
