### ISSUE TITLE
你好我的CPU是i7-12700 但是睿频达不到4GHz，最高锁到了3.7GHz

### ISSUE THREAD

**Issue by 52funny** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#8]
如图这是以下配置

![iShot_2023-06-20_10.24.46.png](https://s1.locimg.com/2023/06/20/f1c7edd088004.png)

![iShot_2023-06-20_10.27.21.png](https://s1.locimg.com/2023/06/20/e50b6f9500da1.png)

**Comment by igarashikenshin** [comment]
尝试更换Kexts/CPUFriendDataProvider.kext
