### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by LwdAmazing** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#9]
硬件配置和您基本一致。引导也无改动，现在有几个情况，
1.进度条后半段黑屏，然后直接进入登录界面，无伤大雅，但是心里不太清楚是不是哪里有问题？
2.我的显示器是4k160hz，每次开机进入后都会跳到60hz，手动更改120hz ,而且在改之前，整体色彩发白，改完就好了。
3.OC截面分辨率无法调整，一直都是1080P。
还望大佬指点一二

**Comment by igarashikenshin** [comment]
显卡vbios是否支持uefi gop？
若不支持，在引导阶段会出现分辨率二次变更的情况
另外检查nvram是否正常工作
除此之外，显示器本身也是一大因素
